name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - python_version: 3.8
            toxenv: py38
          - python_version: 3.7
            toxenv: py37            
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.environment['python-version'] }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.environment['python-version'] }}
    - name: Install tox
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: |
        python -m tox -e ${{ matrix.environment['toxenv'] }}
